_BASE_: "../Base-RCNN-FPN-OPENDET-GMM.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 31
    NUM_KNOWN_CLASSES: 10
DATASETS:
  TRAIN: ('fair1m_train',)
  TEST: ('fair1m_val',
        'fair1m_val_mar20_train_10_20',
        'fair1m_val_mar20_train_10_30')
INPUT:
  MIN_SIZE_TRAIN: (1024, )
  MAX_SIZE_TRAIN: 20000
  # We don't need MAX_SIZE_TRAIN here since we hope crop from a whole slide images
  # MAX_SIZE_TRAIN: 1024 
  MIN_SIZE_TEST: 800
  CROP:
    ENABLED: true
    SIZE: (1024, 1024)
    TYPE: 'absolute'
TEST:
  EVAL_PERIOD: 1200
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (5000, 6800)
  MAX_ITER: 7600
  WARMUP_ITERS: 100
  AMP:
    ENABLED: True

# UPLOSS.WEIGHT: former two are 0.5, the last is 1.0