_BASE_: "../Base-RCNN-FPN-OPENDET-GMM.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 31
    NUM_KNOWN_CLASSES: 10
DATASETS:
  TRAIN: ('fair1m_train',)
  TEST: ('fair1m_val',
        'fair1m_val_mar20_train_10_20',
        'fair1m_val_mar20_train_10_30')
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (21000, 29000)
  MAX_ITER: 32000
  WARMUP_ITERS: 100
  AMP:
    ENABLED: True

# UPLOSS.WEIGHT: former two are 0.5, the last is 1.0