_BASE_: "../Base-RCNN-FPN-OPENDET.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 31
    NUM_KNOWN_CLASSES: 10
DATASETS:
  TRAIN: ('fair1m_train1024_airplane',)
  TEST: ('fair1m_val1024_airplane',
        'fair1m_val1024_airplane_mar20_train_10_20',
        'fair1m_val1024_airplane_mar20_train_10_30')
DATALOADER:
  NUM_WORKERS: 8
INPUT:
  MIN_SIZE_TRAIN: (1024, )
  MAX_SIZE_TRAIN: 20000
  MAX_SIZE_TEST: 20000 
  MIN_SIZE_TEST: 1024
TEST:
  EVAL_PERIOD: 1500
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (12000, 16500)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 1500
  AMP:
    ENABLED: True

# UPLOSS.WEIGHT: former two are 0.5, the last is 1.0