_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0]]
  PROPOSAL_GENERATOR:
    NAME: "ClsFreeRPN"
  RPN:
    HEAD_NAME: "ClsFreeRPNHead"
    BBOX_REG_LOSS_TYPE: "iou"
    BBOX_REG_LOSS_WEIGHT: 0.5
    POST_NMS_TOPK_TRAIN: 2000
    IOU_THRESHOLDS_OBJECTNESS: [0.1, 0.3]
    POSITIVE_FRACTION_OBJECTNESS: 1.0
    CTR_REG_LOSS_WEIGHT: 0.5
    NMS_THRESH: 1.0
    NMS_THRESH_TEST: 1.0
  ROI_HEADS:
    NAME: "OpensetROIHeads"
    OBJ_SCORE_THRESH_TEST: 0.05
    NMS_THRESH_TEST: 1.0
    KNOWN_SCORE_THRESH: 0.05
    KNOWN_NMS_THRESH: 0.5
    KNOWN_TOPK: 50
    UNKNOWN_SCORE_THRESH: 0.0
    UNKNOWN_NMS_THRESH: 0.5
    UNKNOWN_TOPK: 50
    NUM_CLASSES: 31
    NUM_KNOWN_CLASSES: 10
    UNKNOWN_ID: 1000
  ROI_BOX_HEAD:
    CLS_LOSS_WEIGHT: 0.9
    BBOX_REG_LOSS_WEIGHT: 0.5
    IOU_REG_LOSS_WEIGHT: 0.5
    CLS_AGNOSTIC_BBOX_REG: true
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: True
  PLN:
    EMD_DIM: 256
    ALPHA: 0.1
    BETA: 0.9
    DISTANCE_TYPE: "COS"
    REPS_PER_CLASS: 1
    IOU_THRESHOLD: 0.5
    UNK_THR: 0.23
    LOSS_WEIGHT: 0.5
DATASETS:
  TRAIN: ('fair1m_train1024_airplane',)
  TEST: ('fair1m_val1024_airplane',
        'fair1m_val1024_airplane_mar20_train_10_20',
        'fair1m_val1024_airplane_mar20_train_10_30')
  VAL: 'fair1m_val1024_airplane'
DATALOADER:
  NUM_WORKERS: 8
INPUT:
  MIN_SIZE_TRAIN: (1024, )
  MAX_SIZE_TRAIN: 20000
  MAX_SIZE_TEST: 20000 
  MIN_SIZE_TEST: 1024
TEST:
  EVAL_PERIOD: 1500
  DETECTIONS_PER_IMAGE: 1000
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (6000, 8250)
  MAX_ITER: 9000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 1500
  AMP:
    ENABLED: True

# UPLOSS.WEIGHT: former two are 0.5, the last is 1.0