_BASE_: "../Base-RCNN-FPN-OPENDET.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 11
    NUM_KNOWN_CLASSES: 7
  ROI_BOX_HEAD:
    OUTPUT_LAYERS: "CosineFastRCNNOutputLayers" # baseline use a simple cosine FRCNN

DATASETS:
  TRAIN: ('DIOR_train7_set1',)
  TEST: ('DIORtest_DOTAtrainval_7_3_test_set1', 
        'DOTA_trainval_set1_cls_agn_2000_test', 
        'DOTA_trainval_set1_cls_agn_3000_test',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (21000, 29000)
  MAX_ITER: 32000
  WARMUP_ITERS: 100
  AMP:
    ENABLED: True

# UPLOSS.WEIGHT: former two are 0.5, the last is 1.0