_BASE_: "../Base-RCNN-FPN-OPENDET.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ('DIOR_train7',)
  TEST: ('dior_val', 'dior_10_15_test', 'dior_10_20_test')
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (21000, 29000)
  MAX_ITER: 32000000
  WARMUP_ITERS: 500
  AMP:
    ENABLED: True
    
# UPLOSS.WEIGHT: former two are 0.5, the last is 1.0