_BASE_: "../Base-RCNN-FPN-OPENDET.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 11
    NUM_KNOWN_CLASSES: 7
    NAME: "SIRENOpenSetStandardROIHeads"
  ROI_BOX_HEAD:
    OUTPUT_LAYERS: "SIRENOpenDetFastRCNNOutputLayers"
DATASETS:
  TRAIN: ('DIOR_train7',)
  TEST: ('DIORval_DOTAtrainval_val', 
        'DIORtest_DOTAtrainval_7_3_test', 
        'DIORtest_DOTAtrainval_2500_test', 
        'DIORtest_DOTAtrainval_3500_test')
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.005
  STEPS: (21000, 29000)
  MAX_ITER: 32000
  WARMUP_ITERS: 500
  AMP:
    ENABLED: True

UPLOSS:
  START_ITER: 100
  SAMPLING_METRIC: "min_score"
  TOPK: 3
  ALPHA: 1.0
  WEIGHT: 1.0
ICLOSS:
  OUT_DIM: 128
  QUEUE_SIZE: 256
  IN_QUEUE_SIZE: 16
  BATCH_IOU_THRESH: 0.5
  QUEUE_IOU_THRESH: 0.7
  TEMPERATURE: 0.1
  WEIGHT: 0.1
SIREN:
  LOSS_WEIGHT: 0.1
  PROJECTION_DIM: 64
# UPLOSS.WEIGHT: former two are 0.5, the last is 1.0